"""tasks model

Revision ID: 76f54b6c7113
Revises: 3d525c4baf93
Create Date: 2024-07-25 14:12:18.626543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f54b6c7113'
down_revision = '3d525c4baf93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=11), nullable=True),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['executor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_updated_at'))
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_created_at'))

    op.drop_table('task')
    # ### end Alembic commands ###
